Repository chingu-voyages/v43-tier2-team-14, pull requests merged in 2023-04, with the labels that each got.

#66 Style/responsive wishlist
  backend/index.js
  frontend/index.html
  frontend/src/App.css
  frontend/src/assets/loading2.svg
  frontend/src/assets/react.svg
  frontend/src/components/Footer.jsx
  frontend/src/components/NoContent.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/SidebarItem.jsx
  frontend/src/components/UI/Loading.jsx
  frontend/src/components/book/Book.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/book/BookCard.jsx
  frontend/src/components/book/BookImage.jsx
  frontend/src/components/book/BooksContainer.jsx
  frontend/src/components/wishList/WishEmpty.jsx
  frontend/src/components/wishList/WishListItem.jsx
  frontend/src/components/wishList/WishListWrapper.jsx
  frontend/src/hooks/useFetch.jsx
  frontend/src/hooks/useWishlist.jsx
  frontend/src/pages/Error.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Library.jsx
  frontend/src/pages/WishList.jsx
Labels: enhancement

#73 Style categories
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/book/Book.jsx
  frontend/src/components/book/BookCard.jsx
  frontend/src/components/book/BooksContainer.jsx
  frontend/src/components/book/test.jsx
  frontend/src/components/categories/Categories.jsx
  frontend/src/components/categories/CategoriesNav.jsx
  frontend/src/components/categories/Category.jsx
  frontend/src/components/categories/CategoryCard.jsx
  frontend/src/components/wishList/WishListItem.jsx
  frontend/src/hooks/useWishlist.jsx
  frontend/src/pages/Books.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Root.jsx
Labels: enhancement

#82 Style/homepage
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/CategoriesNav.jsx
  frontend/src/components/Search.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/book/BookCard.jsx
  frontend/src/components/book/BooksContainer.jsx
  frontend/src/components/categories/Categories.jsx
  frontend/src/components/featured/Featured.jsx
  frontend/src/components/featured/FeaturedBookBody.jsx
  frontend/src/components/featured/FeaturedList.jsx
  frontend/src/components/featured/FeaturedListWrapper.jsx
  frontend/src/pages/Books.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Register.jsx
  frontend/src/pages/Root.jsx
  frontend/tailwind.config.cjs
Labels: enhancement

#83 adding backend singlebook with title,featured book Route homepage
  backend/index.js
  backend/routes/books.js
  backend/routes/cart.js
  frontend/src/App.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/featured/FeaturedBook.jsx
  frontend/src/components/featured/FeaturedBookBody.jsx
  frontend/src/components/featured/FeaturedList.jsx
  frontend/src/features/cartStore.jsx
Labels: enhancement

#84 splitting search component and adding usedebounce component for fetch…
  backend/routes/books.js
  frontend/src/components/Search.jsx
  frontend/src/components/book/BooksContainer.jsx
  frontend/src/components/featured/FeaturedBook.jsx
  frontend/src/components/search/Search.jsx
  frontend/src/components/search/SearchWrapper.jsx
  frontend/src/components/user/LoginBtn.jsx
  frontend/src/components/user/LogoutBtn.jsx
  frontend/src/components/user/UserData.jsx
  frontend/src/components/wishList/WishListItem.jsx
  frontend/src/hooks/useDebounce.jsx
  frontend/src/pages/Root.jsx
Labels: bug, enhancement

#93 adding search component and debounce working and search results styli…
  backend/index.js
  backend/models/cartModel.js
  backend/models/userModel.js
  backend/routes/books.js
  frontend/src/components/search/Search.jsx
  frontend/src/components/search/SearchResults.jsx
  frontend/src/hooks/useDebounce.jsx
Labels: enhancement

#94 Feature/homepg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/cart/CartFooter.jsx
  frontend/src/components/cart/CartItem.jsx
  frontend/src/components/cart/CartWrapper.jsx
  frontend/src/components/cart/EmptyCart.jsx
  frontend/src/components/cart/QuantityCounter.jsx
  frontend/src/components/featured/FeaturedBook.jsx
  frontend/src/components/featured/FeaturedBookBody.jsx
  frontend/src/components/featured/FeaturedList.jsx
  frontend/src/components/search/Search.jsx
  frontend/src/pages/Cart.jsx
Labels: enhancement

#96 Fix z-index of search results list
  frontend/src/components/search/SearchResults.jsx
Labels: bug

#98 Development
  README.md
  frontend/.vite/deps_temp_ae185a05/package.json
  frontend/src/components/search/Search.jsx
  frontend/src/components/search/SearchResults.jsx
Labels: enhancement

#99 apply responsive fixes
  frontend/src/App.jsx
  frontend/src/components/book/Book.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/featured/FeaturedBook.jsx
  frontend/src/components/featured/FeaturedBookBody.jsx
  frontend/src/components/featured/FeaturedListWrapper.jsx
  frontend/src/components/search/Search.jsx
  frontend/src/components/search/SearchResults.jsx
  frontend/src/components/search/SearchWrapper.jsx
  frontend/src/pages/FeaturedPage.jsx
Labels: bug, enhancement

#100 Development
  README.md
  frontend/src/App.jsx
  frontend/src/components/book/Book.jsx
  frontend/src/components/book/BookBody.jsx
  frontend/src/components/featured/FeaturedBook.jsx
  frontend/src/components/featured/FeaturedBookBody.jsx
  frontend/src/components/featured/FeaturedListWrapper.jsx
  frontend/src/components/search/Search.jsx
  frontend/src/components/search/SearchResults.jsx
  frontend/src/components/search/SearchWrapper.jsx
  frontend/src/pages/FeaturedPage.jsx
Labels: bug, documentation, enhancement

#101 Feature/cart
  README.md
  backend/models/cartItemModel.js
  backend/models/cartModel.js
  backend/routes/books.js
  backend/routes/cart.js
  frontend/src/hooks/useFetchCart.jsx
Labels: documentation, enhancement
